/**
 * Maps file names and extensions to the custom SVG icons in src/assets/explorer-icon.
 * Returns the icon path (for use as <img src>) or null to fall back to Phosphor.
 * ponytail: pure lookup table, no abstractions.
 */

// Exact filename matches (checked before extension)
const EXACT: Record<string, string> = {
  'readme.md': 'readme',
  'readme': 'readme',
  'changelog.md': 'changelog',
  'changelog': 'changelog',
  'license': 'license',
  'license.md': 'license',
  'makefile': 'makefile',
  'dockerfile': 'docker',
  'docker-compose.yml': 'docker',
  'docker-compose.yaml': 'docker',
  '.gitignore': 'git',
  '.gitattributes': 'git',
  '.gitmodules': 'git',
  'package.json': 'npm',
  'package-lock.json': 'npm-lock',
  'yarn.lock': 'yarn-lock',
  'bun.lock': 'bun-lock',
  'bun.lockb': 'bun-lock',
  'tsconfig.json': 'typescript-config',
  'jsconfig.json': 'javascript-config',
  'tailwind.config.js': 'tailwind',
  'tailwind.config.ts': 'tailwind',
  'tailwind.config.mjs': 'tailwind',
  'vite.config.ts': 'vite',
  'vite.config.js': 'vite',
  'next.config.js': 'next',
  'next.config.ts': 'next',
  'next.config.mjs': 'next',
  'nuxt.config.ts': 'nuxt',
  'nuxt.config.js': 'nuxt',
  '.eslintrc': 'eslint',
  '.eslintrc.js': 'eslint',
  '.eslintrc.json': 'eslint',
  '.eslintrc.yaml': 'eslint',
  '.eslintrc.yml': 'eslint',
  'eslint.config.js': 'eslint',
  'eslint.config.mjs': 'eslint',
  'cargo.toml': 'rust-config',
  'cargo.lock': 'rust-config',
  'go.mod': 'go-mod',
  'go.sum': 'go-mod',
  'todo.md': 'todo',
  'todo': 'todo',
  'security.md': 'security',
  'code_of_conduct.md': 'code-of-conduct',
  '.cursorrules': 'cursor',
  'gemini.md': 'gemini-ai',
  '.env': 'key',
  '.env.local': 'key',
  '.env.production': 'key',
  '.env.development': 'key',
};

// Extension → icon name
const EXT: Record<string, string> = {
  // Web
  ts: 'typescript',
  tsx: 'react-typescript',
  js: 'javascript',
  jsx: 'react',
  mjs: 'javascript',
  cjs: 'javascript',
  html: 'html',
  css: 'css',
  scss: 'scss',
  pcss: 'pcss',
  vue: 'vue',
  svelte: 'svelte',
  astro: 'astro',
  // Data / config
  json: 'json',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  xml: 'xml',
  csv: 'csv',
  // Docs
  md: 'markdown',
  mdx: 'markdownx',
  pdf: 'pdf',
  txt: 'text',
  tex: 'latex',
  // Systems / languages
  rs: 'rust',
  go: 'go',
  py: 'python',
  rb: 'ruby',
  java: 'java',
  kt: 'kotlin',
  swift: 'swift',
  c: 'c',
  h: 'c-header',
  cpp: 'cpp',
  cc: 'cpp',
  hpp: 'cpp-header',
  cs: 'cs',
  php: 'php',
  lua: 'lua',
  dart: 'dart',
  scala: 'scala',
  nim: 'nim',
  zig: 'zig',
  odin: 'odin',
  gleam: 'gleam',
  nix: 'nix',
  hcl: 'hcl',
  tf: 'terraform',
  perl: 'perl',
  pl: 'perl',
  ps1: 'powershell',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  fish: 'shell',
  asm: 'assembly',
  s: 'assembly',
  wasm: 'web-assembly',
  julia: 'julia',
  jl: 'julia',
  r: 'event',
  // Media
  png: 'image',
  jpg: 'image',
  jpeg: 'image',
  gif: 'image',
  webp: 'image',
  ico: 'image',
  bmp: 'image',
  tiff: 'image',
  svg: 'svg',
  mp3: 'audio',
  wav: 'audio',
  ogg: 'audio',
  flac: 'audio',
  aac: 'audio',
  mp4: 'video',
  mov: 'video',
  avi: 'video',
  mkv: 'video',
  webm: 'video',
  // Fonts
  ttf: 'font',
  otf: 'font',
  woff: 'font',
  woff2: 'font',
  // Archives
  zip: 'zip',
  gz: 'zip',
  tar: 'zip',
  '7z': 'zip',
  rar: 'zip',
  // Database
  db: 'database',
  sqlite: 'database',
  sql: 'database',
  // Misc
  lock: 'lock',
  pem: 'key',
  cert: 'key',
  key: 'key',
  log: 'text',
  cfg: 'config',
  conf: 'config',
  ini: 'config',
  env: 'key',
};

// Folder name → icon name (without the folder_ prefix)
const FOLDER_NAMES: Record<string, string> = {
  assets: 'assets',
  asset: 'assets',
  audio: 'audio',
  sounds: 'audio',
  auth: 'auth',
  authentication: 'auth',
  bin: 'bin',
  components: 'component',
  component: 'component',
  ui: 'component',
  config: 'config',
  configs: 'config',
  configuration: 'config',
  database: 'database',
  db: 'database',
  dist: 'dist',
  build: 'dist',
  out: 'dist',
  docs: 'docs',
  doc: 'docs',
  documentation: 'docs',
  error: 'error',
  errors: 'error',
  fonts: 'fonts',
  font: 'fonts',
  functions: 'function',
  function: 'function',
  '.github': 'github',
  github: 'github',
  hooks: 'hooks',
  hook: 'hooks',
  images: 'image',
  image: 'image',
  img: 'image',
  photos: 'camera',
  json: 'json',
  layouts: 'layout',
  layout: 'layout',
  lib: 'lib',
  libs: 'lib',
  helpers: 'lib',
  helpers_: 'lib',
  utils: 'util',
  util: 'util',
  middlewares: 'middleware',
  middleware: 'middleware',
  models: 'model',
  model: 'model',
  modules: 'module',
  module: 'module',
  'node_modules': 'node',
  pages: 'page',
  page: 'page',
  views: 'page',
  providers: 'provider',
  provider: 'provider',
  routes: 'routes',
  route: 'routes',
  router: 'routes',
  scripts: 'script',
  script: 'script',
  server: 'server',
  services: 'service',
  service: 'service',
  src: 'source',
  source: 'source',
  storybook: 'storybook',
  '.storybook': 'storybook',
  styles: 'styles',
  style: 'styles',
  css: 'styles',
  svg: 'svg',
  svgs: 'svg',
  icons: 'svg',
  temp: 'temp',
  tmp: 'temp',
  templates: 'template',
  template: 'template',
  tests: 'test',
  test: 'test',
  '__tests__': 'test',
  spec: 'test',
  specs: 'test',
  types: 'types',
  type: 'types',
  typescript: 'typescript',
  ts: 'typescript',
  videos: 'video',
  video: 'video',
  '.vscode': 'vscode',
  vscode: 'vscode',
  web: 'web',
  yarn: 'yarn',
  context: 'context',
  contexts: 'context',
  constants: 'constant',
  constant: 'constant',
  admin: 'admin',
  administration: 'admin',
  animation: 'animation',
  animations: 'animation',
  effects: 'effects',
  effect: 'effects',
  events: 'event',
  event: 'event',
  connection: 'connection',
  connections: 'connection',
  commands: 'commands',
  command: 'commands',
  changesets: 'changesets',
  '.changeset': 'changesets',
  content: 'content',
  benchmark: 'benchmark',
  benchmarks: 'benchmark',
  coverage: 'coverage',
  client: 'client',
  builder: 'builder',
  builders: 'builder',
  packages: 'package',
  package: 'package',
  input: 'input',
  inputs: 'input',
  marketing: 'marketing',
  server_: 'server',
};

const BASE = '/src/assets/explorer-icon';

export function getFolderIconSrc(name: string, open = false): string {
  const key = name.toLowerCase().replace(/\s+/g, '_');
  const variant = FOLDER_NAMES[key];
  const suffix = open ? '_open' : '';
  if (variant) return `${BASE}/folder_${variant}${suffix}.svg`;
  return open ? `${BASE}/_folder_open.svg` : `${BASE}/_folder.svg`;
}

export function getFileIconSrc(name: string): string | null {
  const lower = name.toLowerCase();
  // 1. Exact filename match
  if (EXACT[lower]) return `${BASE}/${EXACT[lower]}.svg`;
  // 2. Extension match
  const ext = lower.split('.').pop();
  if (ext && EXT[ext]) return `${BASE}/${EXT[ext]}.svg`;
  // 3. Generic file
  return `${BASE}/_file.svg`;
}
