import type { MockDomain, MockRoute, RequestLog } from './types';

export const MOCK_DOMAINS: MockDomain[] = [
  {
    id: 'd1',
    hostname: 'api.payment-gateway.local',
    ssl: true,
    status: 'active',
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'd2',
    hostname: 'auth.service.local',
    ssl: true,
    status: 'active',
    createdAt: '2026-07-02T08:30:00Z',
  },
  {
    id: 'd3',
    hostname: 'cdn.assets.mock',
    ssl: false,
    status: 'inactive',
    createdAt: '2026-07-03T14:00:00Z',
  },
];

export const MOCK_ROUTES: MockRoute[] = [
  {
    id: 'r1',
    domainId: 'd1',
    method: 'GET',
    path: '/v1/payments/:id',
    statusCode: 200,
    responseBody: JSON.stringify({ id: ':id', status: 'success', amount: 9900, currency: 'USD' }, null, 2),
    responseHeaders: { 'Content-Type': 'application/json' },
    matchers: [],
    chaos: { latencyMode: 'fixed', latencyFixed: 200, errorRate: 5, errorStatus: 502 },
    enabled: true,
    requestQueryParams: [
      { key: 'verbose', value: 'true', enabled: true },
      { key: 'expand', value: 'customer', enabled: false }
    ],
  },
  {
    id: 'r2',
    domainId: 'd1',
    method: 'POST',
    path: '/v1/payments',
    statusCode: 201,
    responseBody: JSON.stringify({ id: 'pay_new123', status: 'pending' }, null, 2),
    responseHeaders: { 'Content-Type': 'application/json' },
    matchers: [{ headerKey: 'Authorization', headerValue: 'Bearer mock-token' }],
    chaos: { latencyMode: 'random', latencyMin: 100, latencyMax: 800 },
    enabled: true,
    requestBody: JSON.stringify({ amount: 9900, currency: 'USD', customer_id: 'cust_123' }, null, 2),
  },
  {
    id: 'r3',
    domainId: 'd2',
    method: 'POST',
    path: '/auth/login',
    statusCode: 200,
    responseBody: JSON.stringify({ token: 'mock-jwt-token', expiresIn: 3600 }, null, 2),
    responseHeaders: { 'Content-Type': 'application/json' },
    matchers: [],
    chaos: { latencyMode: 'none' },
    enabled: true,
    requestBody: JSON.stringify({ username: 'admin', password: 'password123' }, null, 2),
  },
  {
    id: 'r4',
    domainId: 'd2',
    method: 'GET',
    path: '/auth/me',
    statusCode: 401,
    responseBody: JSON.stringify({ error: 'Unauthorized' }, null, 2),
    responseHeaders: { 'Content-Type': 'application/json' },
    matchers: [],
    chaos: { latencyMode: 'none', errorRate: 15, errorStatus: 401 },
    enabled: false,
    requestQueryParams: [],
  },
];

export const MOCK_LOGS: RequestLog[] = [
  {
    id: 'l1',
    domainId: 'd1',
    routeId: 'r1',
    method: 'GET',
    path: '/v1/payments/pay_abc123',
    statusCode: 200,
    latencyMs: 212,
    timestamp: '2026-07-05T11:01:00Z',
    requestHeaders: { Authorization: 'Bearer mock-token', Accept: 'application/json' },
    requestBody: null,
  },
  {
    id: 'l2',
    domainId: 'd1',
    routeId: 'r2',
    method: 'POST',
    path: '/v1/payments',
    statusCode: 201,
    latencyMs: 456,
    timestamp: '2026-07-05T11:02:30Z',
    requestHeaders: { Authorization: 'Bearer mock-token', 'Content-Type': 'application/json' },
    requestBody: JSON.stringify({ amount: 2500, currency: 'USD' }),
  },
  {
    id: 'l3',
    domainId: 'd1',
    routeId: 'r1',
    method: 'GET',
    path: '/v1/payments/pay_xyz999',
    statusCode: 502,
    latencyMs: 198,
    timestamp: '2026-07-05T11:03:10Z',
    requestHeaders: { Authorization: 'Bearer mock-token' },
    requestBody: null,
  },
  {
    id: 'l4',
    domainId: 'd2',
    routeId: 'r3',
    method: 'POST',
    path: '/auth/login',
    statusCode: 200,
    latencyMs: 80,
    timestamp: '2026-07-05T11:04:00Z',
    requestHeaders: { 'Content-Type': 'application/json' },
    requestBody: JSON.stringify({ username: 'dev@test.com', password: 'hunter2' }),
  },
  {
    id: 'l5',
    domainId: 'd1',
    routeId: null,
    method: 'DELETE',
    path: '/v1/payments/pay_old',
    statusCode: 404,
    latencyMs: 12,
    timestamp: '2026-07-05T11:05:00Z',
    requestHeaders: {},
    requestBody: null,
  },
];
