use crate::scanner::{AiExplanation, Finding};

/// Generate a Markdown report from findings and AI explanations.
pub fn generate_markdown_report(
    scan_root: &str,
    findings: &[Finding],
    explanations: &std::collections::HashMap<String, AiExplanation>,
    files_scanned: usize,
    duration_ms: u64,
) -> String {
    let now = chrono::Utc::now().format("%Y-%m-%d %H:%M UTC").to_string();
    let duration_sec = duration_ms as f64 / 1000.0;

    let mut report = String::new();

    // ── Header ──
    report.push_str(&format!(
        "# Security Audit Report\n\n\
         **Scan root:** `{}`\n\
         **Generated:** {}\n\
         **Files scanned:** {}\n\
         **Duration:** {:.1}s\n\
         **Total findings:** {}\n\n\
         ---\n\n",
        scan_root, now, files_scanned, duration_sec, findings.len()
    ));

    if findings.is_empty() {
        report.push_str("## ✅ No security issues found\n\n");
        report.push_str("The audit did not detect any secrets, dependency vulnerabilities, or suspicious code patterns.\n\n");
        report.push_str("*Note: This is a static analysis — always combine with dynamic testing and manual review.*\n");
        return report;
    }

    // ── Executive Summary ──
    let critical = findings.iter().filter(|f| f.severity == "critical").count();
    let high = findings.iter().filter(|f| f.severity == "high").count();
    let medium = findings.iter().filter(|f| f.severity == "medium").count();
    let low = findings.iter().filter(|f| f.severity == "low").count();
    let info = findings.iter().filter(|f| f.severity == "info").count();

    report.push_str("## Executive Summary\n\n");
    report.push_str(&format!(
        "| Severity | Count |\n\
         |---|---:|\n\
         | 🔴 Critical | {} |\n\
         | 🟠 High | {} |\n\
         | 🟡 Medium | {} |\n\
         | 🔵 Low | {} |\n\
         | ⚪ Info | {} |\n\n",
        critical, high, medium, low, info
    ));

    let categories: std::collections::HashMap<&str, usize> =
        findings.iter().fold(std::collections::HashMap::new(), |mut acc, f| {
            *acc.entry(f.category.as_str()).or_insert(0) += 1;
            acc
        });

    report.push_str("### By Category\n\n");
    report.push_str("| Category | Count |\n|---|---:|\n");
    for (cat, count) in &categories {
        report.push_str(&format!("| {} | {} |\n", cat, count));
    }
    report.push_str("\n---\n\n");

    // ── Critical Findings ──
    if critical > 0 {
        report.push_str("## 🔴 Critical Findings\n\n");
        for finding in findings.iter().filter(|f| f.severity == "critical") {
            write_finding_section(&mut report, finding, explanations);
        }
    }

    // ── High Findings ──
    if high > 0 {
        report.push_str("## 🟠 High Severity Findings\n\n");
        for finding in findings.iter().filter(|f| f.severity == "high") {
            write_finding_section(&mut report, finding, explanations);
        }
    }

    // ── Medium Findings ──
    if medium > 0 {
        report.push_str("## 🟡 Medium Severity Findings\n\n");
        for finding in findings.iter().filter(|f| f.severity == "medium") {
            write_finding_section(&mut report, finding, explanations);
        }
    }

    // ── Low Findings ──
    if low > 0 {
        report.push_str("## 🔵 Low Severity Findings\n\n");
        for finding in findings.iter().filter(|f| f.severity == "low") {
            write_finding_section(&mut report, finding, explanations);
        }
    }

    // ── Info ──
    if info > 0 {
        report.push_str("## ⚪ Informational\n\n");
        for finding in findings.iter().filter(|f| f.severity == "info") {
            write_finding_section(&mut report, finding, explanations);
        }
    }

    // ── Remediation Summary ──
    report.push_str("---\n\n## Remediation Summary\n\n");
    report.push_str("### Immediate Actions\n\n");
    for finding in findings.iter().filter(|f| f.severity == "critical" || f.severity == "high") {
        report.push_str(&format!(
            "- **[{}]** {} — `{}`\n",
            finding.id, finding.title, finding.file_path
        ));
    }
    report.push_str("\n### Recommended Practices\n\n");
    report.push_str("- Rotate all exposed credentials immediately\n");
    report.push_str("- Update vulnerable dependencies to patched versions\n");
    report.push_str("- Use environment variables for secrets, never hardcode them\n");
    report.push_str("- Run `npm audit` / `cargo audit` / `pip-audit` regularly\n");
    report.push_str("- Set up pre-commit hooks to prevent secret leaks (e.g., git-secrets, truffleHog)\n");
    report.push_str("- Enable automated dependency updates (Dependabot / Renovate)\n\n");

    report.push_str("---\n\n*Report generated by 0xBuffer Code Audit*\n");

    report
}

fn write_finding_section(
    report: &mut String,
    finding: &Finding,
    explanations: &std::collections::HashMap<String, AiExplanation>,
) {
    report.push_str(&format!(
        "### {} — {}\n\n",
        finding.id, finding.title
    ));

    report.push_str(&format!(
        "**Severity:** {} | **Rule:** `{}` | **Category:** `{}`\n\n",
        finding.severity.to_uppercase(),
        finding.rule_id,
        finding.category
    ));

    let location = if let Some(line) = finding.line {
        format!("`{}:{}`", finding.file_path, line)
    } else {
        format!("`{}`", finding.file_path)
    };
    report.push_str(&format!("**Location:** {}\n\n", location));

    // Code snippet
    if !finding.snippet.is_empty() {
        report.push_str("```\n");
        report.push_str(&finding.snippet);
        report.push_str("\n```\n\n");
    }

    // Matched text
    if !finding.match_text.is_empty() && finding.match_text != "[REDACTED]" {
        report.push_str(&format!("**Matched:** `{}`\n\n", finding.match_text));
    }

    // AI explanation
    if let Some(exp) = explanations.get(&finding.id) {
        if !exp.explanation.is_empty() {
            report.push_str(&format!("**Analysis:** {}\n\n", exp.explanation));
        }
        if !exp.fix_suggestion.is_empty() {
            report.push_str(&format!("**Fix:** {}\n\n", exp.fix_suggestion));
        }
        if let Some(ref sev) = exp.ai_severity {
            report.push_str(&format!("**AI Severity Assessment:** {}\n\n", sev.to_uppercase()));
        }
    }

    report.push_str("---\n\n");
}
