export const NON_ACTIONABLE_FIELD_TYPES = new Set(['hidden', 'submit', 'button', 'reset', 'image']);
export const MAX_EVIDENCE_ITEMS = 5;

export const PATTERNS = {
  auth: /\b(sign\s*in|log\s*in|login|logout|password|passwd|username|user\s*name|authenticate|authentication|session|oauth|sso|saml)\b/i,
  admin: /\b(admin|administrator|manage|dashboard|console|control[-_\s]*panel|cpanel|wp-admin)\b/i,
  upload: /\b(upload|avatar|attachment|document|media|file)\b/i,
  token: /\b(otp|mfa|2fa|csrf|xsrf|nonce|token|verification|verify|code|captcha)\b/i,
  api: /(?:\/api(?:\/|$)|graphql|graphiql|swagger|openapi|api-docs|redoc|\.json(?:\?|$)|\.well-known)/i,
  secrets: /\b(api[-_\s]*key|access[-_\s]*token|secret|bearer|jwt|private[-_\s]*key|client[-_\s]*secret)\b/i,
  payment: /\b(payment|checkout|billing|invoice|card\s*number|credit\s*card|cvv|cvc|stripe|paypal)\b/i,
  riskyAction: /\b(delete|destroy|remove|reset|disable|deactivate|terminate|revoke|purge|drop)\b/i,
  bulkFlow: /\b(bulk|batch|import|export|download|upload|sync|report|invoice|ticket|order|comment|vote|coupon|transfer|approve|invite|booking)\b/i,
  businessFlow: /\b(checkout|payment|billing|transfer|tickets?|orders?|bookings?|coupons?|comments?|votes?|approve|approval|invite|signup|registration)\b/i,
  crypto: /\b(crypto|encrypt|decrypt|hash|cipher|tls|ssl|certificate|cert|key|jwt|bearer|oauth|saml|password[-_\s]*reset)\b/i,
  debug: /\b(debug|trace|stack\s*trace|exception|phpinfo|server[-_\s]*status|actuator|heapdump|metrics|console|devtools|directory listing|index of)\b/i,
  dependency: /\b(package[-_\s]*lock|yarn\.lock|composer\.lock|gemfile\.lock|node_modules|webpack|source[-_\s]*map|sourcemap|cdn|dependency|dependencies|library|version|outdated|vulnerable)\b/i,
  endpointInventory: /\b(v[0-9]+|beta|alpha|deprecated|legacy|internal|private|debug|test|staging|swagger|openapi|redoc|graphiql|graphql|api[-_\s]*docs)\b/i,
  exceptionHandling: /\b(error|exception|stack\s*trace|traceback|fatal|warning|undefined|null pointer|internal server error|sql error)\b/i,
  integrity: /\b(webhook|callback|redirect[-_\s]*uri|return[-_\s]*url|next=|continue=|signature|signed|checksum|integrity|sri|update|plugin|extension|package)\b/i,
  injection: /\b(sql|query|search|filter|where|select|insert|update|delete|xss|script|template|command|cmd|exec|shell|xpath|ldap|graphql)\b/i,
  objectId: /(?:\/|_|-|\b)(?:id|uuid|guid|user|account|customer|tenant|org|organization|project|order|invoice|file|document)(?:\/|_|-|\b)|\/[0-9a-f]{8,}(?:[/?#]|$)|\/\d{2,}(?:[/?#]|$)/i,
  ssrf: /\b(url|uri|endpoint|callback|webhook|proxy|fetch|request|redirect|remote|avatar|image[-_\s]*url|feed|import[-_\s]*url)\b/i,
  thirdParty: /\b(third[-_\s]*party|external|partner|integration|webhook|callback|oauth|sso|stripe|paypal|slack|github|google|aws|s3)\b/i,
};

export const OWASP_WEB_TOP_10_2025 = [
  {
    code: 'A01:2025',
    type: 'owasp-web-a01-broken-access-control',
    title: 'OWASP A01 Broken Access Control indicator',
    severity: 'medium',
    description: 'The page exposes access-control-sensitive routes or controls that should be reviewed for authorization boundaries.',
  },
  {
    code: 'A02:2025',
    type: 'owasp-web-a02-security-misconfiguration',
    title: 'OWASP A02 Security Misconfiguration indicator',
    severity: 'medium',
    description: 'The page references debug, documentation, configuration, or operational surfaces that may indicate misconfiguration exposure.',
  },
  {
    code: 'A03:2025',
    type: 'owasp-web-a03-software-supply-chain-failures',
    title: 'OWASP A03 Software Supply Chain indicator',
    severity: 'low',
    description: 'The page references dependency, build, package, source map, or third-party library details worth reviewing for supply-chain exposure.',
  },
  {
    code: 'A04:2025',
    type: 'owasp-web-a04-cryptographic-failures',
    title: 'OWASP A04 Cryptographic Failures indicator',
    severity: 'medium',
    description: 'The page references secrets, tokens, keys, certificates, or transport security details that should be reviewed for sensitive data handling.',
  },
  {
    code: 'A05:2025',
    type: 'owasp-web-a05-injection',
    title: 'OWASP A05 Injection indicator',
    severity: 'medium',
    description: 'The page includes query-like inputs, endpoints, or parameters that should be reviewed for injection handling.',
  },
  {
    code: 'A06:2025',
    type: 'owasp-web-a06-insecure-design',
    title: 'OWASP A06 Insecure Design indicator',
    severity: 'low',
    description: 'The page exposes business workflows or state-changing actions that should be reviewed for abuse cases and workflow protections.',
  },
  {
    code: 'A07:2025',
    type: 'owasp-web-a07-authentication-failures',
    title: 'OWASP A07 Authentication Failures indicator',
    severity: 'medium',
    description: 'The page exposes authentication or credential-handling surfaces that should be reviewed for authentication controls.',
  },
  {
    code: 'A08:2025',
    type: 'owasp-web-a08-integrity-failures',
    title: 'OWASP A08 Integrity Failures indicator',
    severity: 'medium',
    description: 'The page references upload, callback, redirect, update, or package flows that should be reviewed for integrity protections.',
  },
  {
    code: 'A09:2025',
    type: 'owasp-web-a09-logging-alerting-failures',
    title: 'OWASP A09 Logging and Alerting indicator',
    severity: 'low',
    description: 'The page references logging, audit, monitoring, or alerting surfaces that should be reviewed for operational exposure and coverage.',
  },
  {
    code: 'A10:2025',
    type: 'owasp-web-a10-exception-handling',
    title: 'OWASP A10 Mishandling of Exceptional Conditions indicator',
    severity: 'low',
    description: 'The page returned an error or exposed exception-like content that should be reviewed for safe error handling.',
  },
];

export const OWASP_API_TOP_10_2023 = [
  {
    code: 'API1:2023',
    type: 'owasp-api1-bola',
    title: 'OWASP API1 Broken Object Level Authorization indicator',
    severity: 'medium',
    description: 'API-like routes expose object identifiers or resource-specific paths that should be reviewed for object-level authorization checks.',
  },
  {
    code: 'API2:2023',
    type: 'owasp-api2-broken-authentication',
    title: 'OWASP API2 Broken Authentication indicator',
    severity: 'medium',
    description: 'API authentication, token, or session surfaces should be reviewed for authentication implementation weaknesses.',
  },
  {
    code: 'API3:2023',
    type: 'owasp-api3-bopla',
    title: 'OWASP API3 Broken Object Property Level Authorization indicator',
    severity: 'medium',
    description: 'API fields or object-property style parameters should be reviewed for excessive data exposure or unsafe property updates.',
  },
  {
    code: 'API4:2023',
    type: 'owasp-api4-unrestricted-resource-consumption',
    title: 'OWASP API4 Unrestricted Resource Consumption indicator',
    severity: 'medium',
    description: 'High-volume or resource-heavy API flows should be reviewed for quotas, pagination, and rate limits.',
  },
  {
    code: 'API5:2023',
    type: 'owasp-api5-broken-function-level-authorization',
    title: 'OWASP API5 Broken Function Level Authorization indicator',
    severity: 'medium',
    description: 'Administrative or privileged API-like functions should be reviewed for function-level authorization checks.',
  },
  {
    code: 'API6:2023',
    type: 'owasp-api6-sensitive-business-flows',
    title: 'OWASP API6 Sensitive Business Flow indicator',
    severity: 'medium',
    description: 'API-accessible business flows should be reviewed for automation abuse and business-impact controls.',
  },
  {
    code: 'API7:2023',
    type: 'owasp-api7-ssrf',
    title: 'OWASP API7 Server Side Request Forgery indicator',
    severity: 'medium',
    description: 'API inputs or routes reference URLs, callbacks, webhooks, proxies, or remote fetch behavior that should be reviewed for SSRF protections.',
  },
  {
    code: 'API8:2023',
    type: 'owasp-api8-security-misconfiguration',
    title: 'OWASP API8 Security Misconfiguration indicator',
    severity: 'medium',
    description: 'API documentation, debug, operational, or configuration surfaces should be reviewed for misconfiguration exposure.',
  },
  {
    code: 'API9:2023',
    type: 'owasp-api9-improper-inventory',
    title: 'OWASP API9 Improper Inventory Management indicator',
    severity: 'low',
    description: 'Versioned, deprecated, documentation, debug, or environment-specific API routes should be reviewed for inventory management.',
  },
  {
    code: 'API10:2023',
    type: 'owasp-api10-unsafe-consumption-of-apis',
    title: 'OWASP API10 Unsafe Consumption of APIs indicator',
    severity: 'low',
    description: 'Third-party, integration, callback, webhook, or partner API flows should be reviewed for unsafe external API consumption.',
  },
];
