import { listen } from '@tauri-apps/api/event';
import { useEffect } from 'react';
import { useTargetStore } from '@/stores/target';
import { useDocumentsStore } from '@/stores/documents';

interface AddTargetPayload {
  host: string;
  name: string | null;
}

interface WriteDocumentPayload {
  documentId: string | null;
  sectionKey: string | null;
  title: string | null;
  content: string;
  mode: 'append' | 'replace';
}

export function useAiChatActions() {
  useEffect(() => {
    const unlistenAddTarget = listen<AddTargetPayload>(
      'ai-action-add-target',
      (event) => {
        const { host, name } = event.payload;
        if (!host) return;

        const target = useTargetStore.getState().addHostTarget(host);
        if (target && name) {
          useTargetStore.getState().updateTarget(target.id, { name });
        }
      }
    );

    const unlistenWriteDocument = listen<WriteDocumentPayload>(
      'ai-action-write-document',
      (event) => {
        const { documentId, sectionKey, title, content, mode } = event.payload;
        if (!content) return;

        const docStore = useDocumentsStore.getState();
        const targetDocId = documentId || docStore.activeDocumentId;

        if (!targetDocId) return;

        if (sectionKey) {
          // Update existing custom section
          docStore.updateDocument(targetDocId, (doc) => {
            const existingSection = doc.customSections.find(
              (s) => s.key === sectionKey
            );
            if (!existingSection) return doc;

            const updatedContent =
              mode === 'replace'
                ? content
                : `${existingSection.content}\n\n${content}`.trim();

            return {
              ...doc,
              customSections: doc.customSections.map((s) =>
                s.key === sectionKey
                  ? { ...s, content: updatedContent }
                  : s
              ),
            };
          });
        } else {
          // Create a new custom section
          docStore.addCustomSection(targetDocId, {
            title: title || 'AI Notes',
            description: 'Content generated by the AI Analyst',
            placeholder: '',
            content,
          });
        }
      }
    );

    return () => {
      unlistenAddTarget.then((fn) => fn());
      unlistenWriteDocument.then((fn) => fn());
    };
  }, []);
}
