import { useDocumentsStore } from '@/stores/documents';

export interface WriteDocumentOptions {
  documentId?: string | null;
  sectionKey?: string | null;
  title?: string | null;
  content: string;
  mode?: 'append' | 'replace';
}

export function writeDocument(options: WriteDocumentOptions): void {
  const { documentId, sectionKey, title, content, mode } = options;
  if (!content) return;

  const docStore = useDocumentsStore.getState();
  let targetDocId = documentId || docStore.activeDocumentId;

  // Auto-create a document if none exists
  if (!targetDocId) {
    targetDocId = docStore.addDocument('blank');
  }

  if (sectionKey) {
    const doc = docStore.documents.find((d) => d.id === targetDocId);
    const existing = doc?.customSections.find((s) => s.key === sectionKey);

    if (existing) {
      // Append to or replace existing section
      const updated =
        mode === 'replace' ? content : `${existing.content}\n\n${content}`.trim();
      docStore.updateDocument(targetDocId, (d) => ({
        ...d,
        customSections: d.customSections.map((s) =>
          s.key === sectionKey ? { ...s, content: updated } : s,
        ),
      }));
    } else {
      // Section doesn't exist yet — create it with the requested key
      docStore.updateDocument(targetDocId, (d) => ({
        ...d,
        customSections: [
          ...d.customSections,
          {
            key: sectionKey,
            title: title || sectionKey,
            description: 'Automation workflow output',
            placeholder: '',
            content,
          },
        ],
        updatedAt: new Date().toISOString(),
      }));
    }
  } else {
    // No sectionKey — use a fixed default key so content always goes to the same section
    const defaultKey = 'automation-output';
    const doc = docStore.documents.find((d) => d.id === targetDocId);
    const existing = doc?.customSections.find((s) => s.key === defaultKey);

    if (existing) {
      const updated =
        mode === 'replace' ? content : `${existing.content}\n\n${content}`.trim();
      docStore.updateDocument(targetDocId, (d) => ({
        ...d,
        customSections: d.customSections.map((s) =>
          s.key === defaultKey ? { ...s, content: updated } : s,
        ),
      }));
    } else {
      docStore.updateDocument(targetDocId, (d) => ({
        ...d,
        customSections: [
          ...d.customSections,
          {
            key: defaultKey,
            title: title || 'Automation Output',
            description: 'Content generated by automation workflow',
            placeholder: '',
            content,
          },
        ],
        updatedAt: new Date().toISOString(),
      }));
    }
  }
}
