import { useDocumentsStore } from '@/stores/documents';

export interface WriteDocumentOptions {
  documentId?: string | null;
  sectionKey?: string | null;
  title?: string | null;
  content: string;
  mode?: 'append' | 'replace';
}

export function writeDocument(options: WriteDocumentOptions): void {
  const { documentId, sectionKey, title, content, mode } = options;
  if (!content) return;

  const docStore = useDocumentsStore.getState();
  const targetDocId = documentId || docStore.activeDocumentId;
  if (!targetDocId) return;

  if (sectionKey) {
    docStore.updateDocument(targetDocId, (doc) => {
      const existing = doc.customSections.find((s) => s.key === sectionKey);
      if (!existing) return doc;
      const updated =
        mode === 'replace' ? content : `${existing.content}\n\n${content}`.trim();
      return {
        ...doc,
        customSections: doc.customSections.map((s) =>
          s.key === sectionKey ? { ...s, content: updated } : s,
        ),
      };
    });
  } else {
    docStore.addCustomSection(targetDocId, {
      title: title || 'AI Notes',
      description: 'Content generated by the AI Analyst',
      placeholder: '',
      content,
    });
  }
}
