import type {
  ListenerDashboardStats,
  ListenerInteraction,
  ListenerPayload,
  ListenerServer,
} from './types';

// ── Servers ────────────────────────────────────────────────────────

export const MOCK_SERVERS: ListenerServer[] = [
  {
    id: 'srv-001',
    name: 'Primary Listener',
    url: 'https://collab.apprecon.io',
    apiKey: 'a1b2c3d4e5f6g7h8',
    status: 'connected',
    createdAt: '2026-03-15T08:22:00Z',
    updatedAt: '2026-06-04T09:10:00Z',
  },
  {
    id: 'srv-002',
    name: 'Staging HardDrives',
    url: 'https://staging-collab.apprecon.io',
    apiKey: 'x9y8z7w6v5u4t3s2',
    status: 'connected',
    createdAt: '2026-04-01T14:30:00Z',
    updatedAt: '2026-06-04T08:55:00Z',
  },
  {
    id: 'srv-003',
    name: 'Dev Listener',
    url: 'http://localhost:8787',
    apiKey: 'devkey1234567890',
    status: 'offline',
    createdAt: '2026-05-20T11:00:00Z',
    updatedAt: '2026-06-02T16:45:00Z',
  },
];

// ── Payloads ───────────────────────────────────────────────────────

export const MOCK_PAYLOADS: ListenerPayload[] = [
  {
    id: 'pay-001',
    serverId: 'srv-001',
    identifier: 'a3f8k2',
    payloadUrl: 'a3f8k2.collab.apprecon.io',
    name: 'XSS on Login Form',
    description: 'Blind XSS injected into the username field of /login endpoint',
    tags: '["xss","blind","login"]',
    interactionCount: 12,
    status: 'active',
    createdAt: '2026-05-28T10:15:00Z',
    lastSeenAt: '2026-06-04T09:02:00Z',
  },
  {
    id: 'pay-002',
    serverId: 'srv-001',
    identifier: 'm7p4w1',
    payloadUrl: 'm7p4w1.collab.apprecon.io',
    name: 'SQLi on MagnifyingGlass API',
    description: 'Blind SQLi in the q parameter of /api/search',
    tags: '["sqli","blind","search"]',
    interactionCount: 8,
    status: 'active',
    createdAt: '2026-05-30T14:20:00Z',
    lastSeenAt: '2026-06-04T08:47:00Z',
  },
  {
    id: 'pay-003',
    serverId: 'srv-002',
    identifier: 'z9b1c5',
    payloadUrl: 'z9b1c5.staging-collab.apprecon.io',
    name: 'SSRF in Image Proxy',
    description: 'SSRF via URL parameter in /api/fetch-image',
    tags: '["ssrf","image-proxy"]',
    interactionCount: 5,
    status: 'active',
    createdAt: '2026-06-01T09:00:00Z',
    lastSeenAt: '2026-06-03T22:30:00Z',
  },
  {
    id: 'pay-004',
    serverId: 'srv-001',
    identifier: 'h4d6n8',
    payloadUrl: 'h4d6n8.collab.apprecon.io',
    name: 'XXE on File Upload',
    description: 'XXE payload embedded in SVG file upload',
    tags: '["xxe","file-upload"]',
    interactionCount: 3,
    status: 'active',
    createdAt: '2026-06-02T16:45:00Z',
    lastSeenAt: '2026-06-04T07:15:00Z',
  },
  {
    id: 'pay-005',
    serverId: 'srv-002',
    identifier: 'q2e7r9',
    payloadUrl: 'q2e7r9.staging-collab.apprecon.io',
    name: 'Password Reset Token Leak',
    description: 'OOB check for password reset token exfiltration via Referer header',
    tags: '["token-leak","referer"]',
    interactionCount: 0,
    status: 'active',
    createdAt: '2026-06-03T11:30:00Z',
    lastSeenAt: null,
  },
  {
    id: 'pay-006',
    serverId: 'srv-001',
    identifier: 'j5k3l1',
    payloadUrl: 'j5k3l1.collab.apprecon.io',
    name: 'CSRF on Admin Panel',
    description: 'Archived: CSRF callback test on /admin/settings endpoint',
    tags: '["csrf","admin"]',
    interactionCount: 22,
    status: 'archived',
    createdAt: '2026-04-10T08:00:00Z',
    lastSeenAt: '2026-05-15T19:20:00Z',
  },
  {
    id: 'pay-007',
    serverId: 'srv-003',
    identifier: 'w8x0f3',
    payloadUrl: 'w8x0f3.localhost',
    name: 'RCE Callback Test',
    description: 'Command injection OOB callback for staging',
    tags: '["rce","command-injection"]',
    interactionCount: 1,
    status: 'active',
    createdAt: '2026-06-01T20:00:00Z',
    lastSeenAt: '2026-06-01T20:05:00Z',
  },
];

// ── Interactions ───────────────────────────────────────────────────

export const MOCK_INTERACTIONS: ListenerInteraction[] = [
  {
    id: 'int-001',
    payloadId: 'pay-001',
    interactionType: 'http',
    sourceIp: '192.168.1.45',
    method: 'GET',
    path: '/a3f8k2',
    headers: JSON.stringify({
      Host: 'a3f8k2.collab.apprecon.io',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      Referer: 'https://target-app.com/login',
      Accept: 'image/webp,*/*',
    }),
    rawRequest:
      'GET /a3f8k2 HTTP/1.1\r\nHost: a3f8k2.collab.apprecon.io\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\r\nReferer: https://target-app.com/login\r\nAccept: image/webp,*/*\r\nConnection: keep-alive',
    requestBody: null,
    serverResponse: 'HTTP/1.1 200 OK\r\nContent-Length: 0',
    timestamp: '2026-06-04T09:02:33Z',
  },
  {
    id: 'int-002',
    payloadId: 'pay-001',
    interactionType: 'dns',
    sourceIp: '10.0.0.12',
    method: null,
    path: null,
    headers: null,
    rawRequest: null,
    requestBody: null,
    serverResponse: null,
    timestamp: '2026-06-04T09:02:31Z',
  },
  {
    id: 'int-003',
    payloadId: 'pay-002',
    interactionType: 'https',
    sourceIp: '172.16.0.88',
    method: 'POST',
    path: '/m7p4w1',
    headers: JSON.stringify({
      Host: 'm7p4w1.collab.apprecon.io',
      'User-Agent': 'sqlmap/1.8',
      'Content-TextT': 'application/x-www-form-urlencoded',
      'Content-Length': '42',
    }),
    rawRequest:
      'POST /m7p4w1 HTTP/1.1\r\nHost: m7p4w1.collab.apprecon.io\r\nUser-Agent: sqlmap/1.8\r\nContent-TextT: application/x-www-form-urlencoded\r\n\r\nid=1%27%20AND%201%3D1--',
    requestBody: 'id=1\' AND 1=1--',
    serverResponse: 'HTTP/1.1 200 OK\r\nContent-Length: 0',
    timestamp: '2026-06-04T08:47:12Z',
  },
  {
    id: 'int-004',
    payloadId: 'pay-002',
    interactionType: 'dns',
    sourceIp: '172.16.0.88',
    method: null,
    path: null,
    headers: null,
    rawRequest: null,
    requestBody: null,
    serverResponse: null,
    timestamp: '2026-06-04T08:47:10Z',
  },
  {
    id: 'int-005',
    payloadId: 'pay-003',
    interactionType: 'http',
    sourceIp: '203.0.113.42',
    method: 'GET',
    path: '/z9b1c5?redirect=https://internal.corp/admin',
    headers: JSON.stringify({
      Host: 'z9b1c5.staging-collab.apprecon.io',
      'User-Agent': 'curl/8.1.2',
      Accept: '*/*',
    }),
    rawRequest:
      'GET /z9b1c5?redirect=https://internal.corp/admin HTTP/1.1\r\nHost: z9b1c5.staging-collab.apprecon.io\r\nUser-Agent: curl/8.1.2\r\nAccept: */*',
    requestBody: null,
    serverResponse: 'HTTP/1.1 200 OK\r\nContent-Length: 0',
    timestamp: '2026-06-03T22:30:45Z',
  },
  {
    id: 'int-006',
    payloadId: 'pay-004',
    interactionType: 'http',
    sourceIp: '192.168.1.45',
    method: 'POST',
    path: '/h4d6n8',
    headers: JSON.stringify({
      Host: 'h4d6n8.collab.apprecon.io',
      'User-Agent': 'Mozilla/5.0',
      'Content-TextT': 'image/svg+xml',
    }),
    rawRequest:
      'POST /h4d6n8 HTTP/1.1\r\nHost: h4d6n8.collab.apprecon.io\r\nContent-TextT: image/svg+xml\r\n\r\n<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><svg>&xxe;</svg>',
    requestBody:
      '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><svg>&xxe;</svg>',
    serverResponse: 'HTTP/1.1 200 OK\r\nContent-Length: 0',
    timestamp: '2026-06-04T07:15:22Z',
  },
  {
    id: 'int-007',
    payloadId: 'pay-004',
    interactionType: 'dns',
    sourceIp: '192.168.1.45',
    method: null,
    path: null,
    headers: null,
    rawRequest: null,
    requestBody: null,
    serverResponse: null,
    timestamp: '2026-06-04T07:15:20Z',
  },
  {
    id: 'int-008',
    payloadId: 'pay-001',
    interactionType: 'https',
    sourceIp: '198.51.100.7',
    method: 'GET',
    path: '/a3f8k2?callback=test',
    headers: JSON.stringify({
      Host: 'a3f8k2.collab.apprecon.io',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0)',
      Cookie: 'session=abc123def456',
    }),
    rawRequest:
      'GET /a3f8k2?callback=test HTTP/1.1\r\nHost: a3f8k2.collab.apprecon.io\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0)\r\nCookie: session=abc123def456',
    requestBody: null,
    serverResponse: 'HTTP/1.1 200 OK\r\nContent-Length: 0',
    timestamp: '2026-06-03T18:22:05Z',
  },
  {
    id: 'int-009',
    payloadId: 'pay-003',
    interactionType: 'dns',
    sourceIp: '203.0.113.42',
    method: null,
    path: null,
    headers: null,
    rawRequest: null,
    requestBody: null,
    serverResponse: null,
    timestamp: '2026-06-03T22:30:42Z',
  },
  {
    id: 'int-010',
    payloadId: 'pay-007',
    interactionType: 'http',
    sourceIp: '127.0.0.1',
    method: 'GET',
    path: '/w8x0f3',
    headers: JSON.stringify({
      Host: 'w8x0f3.localhost',
      'User-Agent': 'python-requests/2.31.0',
    }),
    rawRequest:
      'GET /w8x0f3 HTTP/1.1\r\nHost: w8x0f3.localhost\r\nUser-Agent: python-requests/2.31.0',
    requestBody: null,
    serverResponse: 'HTTP/1.1 200 OK\r\nContent-Length: 0',
    timestamp: '2026-06-01T20:05:11Z',
  },
  {
    id: 'int-011',
    payloadId: 'pay-002',
    interactionType: 'http',
    sourceIp: '172.16.0.88',
    method: 'GET',
    path: '/m7p4w1?id=1%27%20UNION%20SELECT%20null--',
    headers: JSON.stringify({
      Host: 'm7p4w1.collab.apprecon.io',
      'User-Agent': 'sqlmap/1.8',
    }),
    rawRequest:
      'GET /m7p4w1?id=1%27%20UNION%20SELECT%20null-- HTTP/1.1\r\nHost: m7p4w1.collab.apprecon.io\r\nUser-Agent: sqlmap/1.8',
    requestBody: null,
    serverResponse: 'HTTP/1.1 200 OK\r\nContent-Length: 0',
    timestamp: '2026-06-03T14:10:00Z',
  },
  {
    id: 'int-012',
    payloadId: 'pay-001',
    interactionType: 'dns',
    sourceIp: '10.0.0.25',
    method: null,
    path: null,
    headers: null,
    rawRequest: null,
    requestBody: null,
    serverResponse: null,
    timestamp: '2026-06-02T11:30:00Z',
  },
];

// ── Dashboard Stats ────────────────────────────────────────────────

export const MOCK_STATS: ListenerDashboardStats = {
  activePayloads: 6,
  interactionsToday: 7,
  dnsEvents: 5,
  httpEvents: 5,
  httpsEvents: 2,
  lastCallback: '2026-06-04T09:02:33Z',
  connectedServers: 2,
};
