import type { AutomationNodeType } from '../types';
import type { NodeProfile } from './node-capability-types';
import {
  ACTION_OUTPUT_BASE,
  CONDITION_OUTPUT,
  HTTP_CONTEXT_INPUT,
  NO_INPUT,
  NO_OUTPUT,
} from './node-schema-fragments';

export const CONDITION_NODE_PROFILES: Partial<Record<AutomationNodeType, NodeProfile>> = {
  'condition:status-code': {
    type: 'condition:status-code',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: HTTP_CONTEXT_INPUT,
      output: CONDITION_OUTPUT,
    },
  },
  'condition:url-contains': {
    type: 'condition:url-contains',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: HTTP_CONTEXT_INPUT,
      output: CONDITION_OUTPUT,
    },
  },
  'condition:body-contains': {
    type: 'condition:body-contains',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: HTTP_CONTEXT_INPUT,
      output: CONDITION_OUTPUT,
    },
  },
  'condition:header-exists': {
    type: 'condition:header-exists',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: HTTP_CONTEXT_INPUT,
      output: CONDITION_OUTPUT,
    },
  },
  'condition:severity': {
    type: 'condition:severity',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: [
        { key: 'severity', label: 'Severity', type: 'string', description: 'Finding severity (info, low, medium, high, critical)' },
        { key: 'host', label: 'Host', type: 'string', description: 'Target host' },
        { key: 'url', label: 'URL', type: 'string', description: 'Related URL' },
        { key: 'timestamp', label: 'Timestamp', type: 'string', description: 'When the finding was created' },
      ],
      output: [
        { key: 'severity', label: 'Severity', type: 'string', description: 'Finding severity' },
        { key: 'host', label: 'Host', type: 'string', description: 'Target host' },
        { key: 'url', label: 'URL', type: 'string', description: 'Related URL' },
        { key: 'timestamp', label: 'Timestamp', type: 'string', description: 'When the finding was created' },
        { key: 'match', label: 'Match', type: 'boolean', description: 'Whether severity matched threshold' },
      ],
    },
  },
  'condition:ai-confidence': {
    type: 'condition:ai-confidence',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: [
        { key: 'confidence', label: 'Confidence', type: 'number', description: 'AI confidence score (0–1)' },
        { key: 'url', label: 'URL', type: 'string', description: 'Analyzed URL' },
        { key: 'host', label: 'Host', type: 'string', description: 'Target host' },
        { key: 'timestamp', label: 'Timestamp', type: 'string', description: 'When analysis completed' },
      ],
      output: [
        { key: 'confidence', label: 'Confidence', type: 'number', description: 'AI confidence score' },
        { key: 'url', label: 'URL', type: 'string', description: 'Analyzed URL' },
        { key: 'host', label: 'Host', type: 'string', description: 'Target host' },
        { key: 'timestamp', label: 'Timestamp', type: 'string', description: 'When analysis completed' },
        { key: 'match', label: 'Match', type: 'boolean', description: 'Whether confidence met threshold' },
      ],
    },
  },
  'condition:method': {
    type: 'condition:method',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: HTTP_CONTEXT_INPUT,
      output: CONDITION_OUTPUT,
    },
  },
  'condition:content-type': {
    type: 'condition:content-type',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: HTTP_CONTEXT_INPUT,
      output: CONDITION_OUTPUT,
    },
  },
  'condition:response-size': {
    type: 'condition:response-size',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: HTTP_CONTEXT_INPUT,
      output: CONDITION_OUTPUT,
    },
  },
  'condition:crawl-status': {
    type: 'condition:crawl-status',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: [
        { key: 'url', label: 'URL', type: 'string', description: 'Crawled page URL' },
        { key: 'statusCode', label: 'Status Code', type: 'number', description: 'HTTP response status' },
        { key: 'host', label: 'Host', type: 'string', description: 'Target hostname' },
        { key: 'timestamp', label: 'Timestamp', type: 'string', description: 'When page was crawled' },
      ],
      output: [
        { key: 'url', label: 'URL', type: 'string', description: 'Crawled page URL' },
        { key: 'statusCode', label: 'Status Code', type: 'number', description: 'HTTP response status' },
        { key: 'host', label: 'Host', type: 'string', description: 'Target hostname' },
        { key: 'timestamp', label: 'Timestamp', type: 'string', description: 'When page was crawled' },
        { key: 'match', label: 'Match', type: 'boolean', description: 'Whether crawl status matched' },
      ],
    },
  },
  'condition:grep-match': {
    type: 'condition:grep-match',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: [
        { key: 'body', label: 'Body', type: 'string', description: 'Text content to search' },
        { key: 'url', label: 'URL', type: 'string', description: 'Source URL' },
        { key: 'host', label: 'Host', type: 'string', description: 'Target host' },
        { key: 'timestamp', label: 'Timestamp', type: 'string', description: 'When data was received' },
      ],
      output: [
        { key: 'body', label: 'Body', type: 'string', description: 'Searched text content' },
        { key: 'url', label: 'URL', type: 'string', description: 'Source URL' },
        { key: 'host', label: 'Host', type: 'string', description: 'Target host' },
        { key: 'timestamp', label: 'Timestamp', type: 'string', description: 'When data was received' },
        { key: 'match', label: 'Match', type: 'boolean', description: 'Whether grep pattern was found' },
      ],
    },
  },
  'condition:port-open': {
    type: 'condition:port-open',
    category: 'condition',
    wired: true,
    reason: null,
    sourceHandleIds: ['true', 'false'],
    sourceHandleLabels: { true: 'True', false: 'False' },
    targetHandleRequired: true,
    dataSchema: {
      input: [
        { key: 'host', label: 'Host', type: 'string', description: 'Target host' },
        { key: 'ports', label: 'Ports', type: 'array', description: 'Discovered open ports' },
        { key: 'timestamp', label: 'Timestamp', type: 'string', description: 'When scan completed' },
      ],
      output: [
        { key: 'host', label: 'Host', type: 'string', description: 'Target host' },
        { key: 'ports', label: 'Ports', type: 'array', description: 'Discovered open ports' },
        { key: 'timestamp', label: 'Timestamp', type: 'string', description: 'When scan completed' },
        { key: 'match', label: 'Match', type: 'boolean', description: 'Whether any port matched the condition' },
      ],
    },
  }
};
